"""auth sessions and ranking

Ranking and the API (PLAN.md §6.6, §8, milestone M7):
- usr.login_tokens and usr.sessions: one-time login links and session cookies (hashes only).
  The score and api roles get them through migration 0002's default privileges.
- usr.user_settings.preset: the survey's ranking preset.
- web.provider_spend.purpose gains `search` (query embeddings).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-23 14:11:55.162065
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

SPEND_PURPOSE_CHECK = "ck_provider_spend_spendpurpose"
SPEND_PURPOSES = ("embed_documents", "embed_topics")


def replace_spend_purposes(purposes: Sequence[str]) -> None:
    # The CHECK that stores the SpendPurpose enum; autogenerate doesn't compare CHECKs.
    op.drop_constraint(op.f(SPEND_PURPOSE_CHECK), "provider_spend", schema="web", type_="check")
    values = ", ".join(f"'{purpose}'" for purpose in purposes)
    op.create_check_constraint(
        op.f(SPEND_PURPOSE_CHECK), "provider_spend", f"purpose IN ({values})", schema="web"
    )


revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_tokens",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usr.users.id"],
            name=op.f("fk_login_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_login_tokens")),
        schema="usr",
    )
    op.create_index(
        op.f("ix_login_tokens_user_id"), "login_tokens", ["user_id"], unique=False, schema="usr"
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usr.users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_sessions")),
        schema="usr",
    )
    op.create_index(
        op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="usr"
    )
    op.add_column(
        "user_settings",
        sa.Column(
            "preset",
            sa.Enum(
                "balanced",
                "trust_my_sources",
                "match_my_interests",
                "fresh",
                name="rankingpreset",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        schema="usr",
    )
    # ### end Alembic commands ###
    replace_spend_purposes([*SPEND_PURPOSES, "search"])


def downgrade() -> None:
    op.execute("DELETE FROM web.provider_spend WHERE purpose = 'search'")
    replace_spend_purposes(SPEND_PURPOSES)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "preset", schema="usr")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions", schema="usr")
    op.drop_table("sessions", schema="usr")
    op.drop_index(op.f("ix_login_tokens_user_id"), table_name="login_tokens", schema="usr")
    op.drop_table("login_tokens", schema="usr")
    # ### end Alembic commands ###
